### ISSUE TITLE
use embedly-proxy for our images

### ISSUE THREAD

**Issue by wresuolc** [mozilla/universal-search-recommendation#102]
We should use a proxy for embedly to avoid giving up our client's IP addresses.  @jaredkerim wrote one at https://github.com/mozilla/embedly-proxy .  Let's use it!

Tim says they are using it successfully in production right now so we should be good to go.

**Comment by wresuolc** [comment]
See https://github.com/mozilla/activity-streams/blob/master/lib/PreviewProvider.js for usage -- there is some caching and sanitization we might be able to use.

**Comment by chuckharmston** [comment]
We don't expose our user's IPs; our server makes the queries to Embedly, not the client.

We should still use an image proxy of some sort; but there are no privacy leaks here, so it's probably very low priority.

**Comment by chuckharmston** [comment]
That was a dumb comment; Embedly proxies the images themselves.

**Comment by chuckharmston** [comment]
I'm going to close this in favor of a [a comment I made](https://github.com/mozilla/universal-search-recommendation/issues/104#issuecomment-213199041) on #104. Neither Embedly nor Clearbit will be our only image sources; we should have a single image proxy to manage it all.
