### ISSUE TITLE
Logging options for nginx-cached results

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/universal-search-recommendation#122]
It just occurred to me that, with the upstream nginx cache, we'll be missing out on server-side logs for the vast majority of our requests.

Are we using `http_proxy_module` for that cache? What are our options for ensuring that those requests are captured? Ideally we'll be able to use [our existing logging middleware](https://github.com/mozilla/universal-search-recommendation/blob/master/recommendation/mozlog/middleware.py) in one fashion or another.

cc @relud

**Comment by relud** [comment]
FYI: we aren't shipping nginx logs to s3 right now. not that we can't, just that we aren't yet.

**Comment by chuckharmston** [comment]
@relud good info, thanks. Are we able to use a specific log formatter for only proxied requests? Do we have any prior art for formatting nginx logs in mozlog format?

**Comment by relud** [comment]
I don't know about specific log formatter, but we don't need to ship nginx logs in mozlog format. they are already in a standard format that we can parse and ship to s3.

**Comment by chuckharmston** [comment]
What can we do to get that started? Ideally we'd be able to line up at least queries with those we collect this way:

https://github.com/mozilla/universal-search/blob/master/docs/metrics.md#on-the-server

**Comment by chuckharmston** [comment]
Summary from an IRC conversation: @relud is going to start shipping these logs ASAP. That will resolve the launch-blocking part of this issue, since at worst, we'll have the logs stored persistently, with PII stripped, in a raw-ish form for later analysis.

Separately, I'll file a separate bug that doesn't block launch to figure out how to get these into whatever formats and systems we need for analysis.

**Comment by chuckharmston** [comment]
@relud Any updates on the final piece of this?

**Comment by relud** [comment]
the final piece was completed on monday.

-Daniel Thorn
Mozilla Services Operations Engineer

**Comment by chuckharmston** [comment]
Fantastic, thanks!
