### ISSUE TITLE
Expand TLD classifier to include top level pages

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/universal-search-recommendation#133]
Criteria:
- It should show domains that link to login pages
- It should show domains that link to localized versions of the page

**Comment by chuckharmston** [comment]
This will be a tricky one; pages structure URLs so differently that there are bound to be outliers to any approach we take. False negatives are better than false positives here.

Proposal: if the URL's path is one of:
- Exactly `` with an optional querystring
- Matches `^\/\w{1,12}[\/\-_]?\w{0,2}\/?$` with no querystring allowed.

So these would all match:
http://example.tld/
http://example.tld/?l=en_US
http://example.tld/en
http://example.tld/en/us
http://example.tld/en-US/
http://example.tld/en_US/
http://example.tld/login
http://example.tld/ipad
http://example.tld/business

And these would all fail:

http://example.tld/somereallylongspammykeywordstuffything
http://example.tld/ual/en/us/
http://example.tld/title/tt1300854
http://example.tld/CreepyParty-Deluxe-Novelty-Halloween-Costume/dp/B0107XRQ7E
http://example.tld/watch?v=awU8M3qVgZQ
http://example.tld/en-US/firefox/new/
http://example.tld/wiki/IPad

**Comment by chuckharmston** [comment]
@nchapman thoughts on the above proposal? There are definitely some misses, most notably United's homepage.

**Comment by hannosch** [comment]
What about ``http://en.example.tld/`` like in ``http://de.yahoo.com``?

**Comment by chuckharmston** [comment]
That'd [already match](https://github.com/mozilla/universal-search-recommendation/blob/master/recommendation/search/classification/tld.py#L21)! This particular user story is for some of the edge cases, like:

- https://www.mozilla.org/en-US/
- http://www.apple.com/ipad/
- https://twitter.com/login

**Comment by hannosch** [comment]
Ah right, got you. One problematic case I can think of is social sites or anything exposing user or project names at the top-level, for example:
* https://twitter.com/mozilla
* https://github.com/mozilla
The regex would classify all of these as tld.

**Comment by nchapman** [comment]
> The regex would classify all of these as tld.

Yeah good point. We could consider augmenting the tld classification to include very specific matches around localization/login, and create a new classification for "top level directories" or something like that.

**Comment by wresuolc** [comment]
it looks great!
