### ISSUE TITLE
Classify searches for movies.

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/universal-search-recommendation#134]
- [x] It should detect that a query is a movie query
- [x] It should show an image (poster) for the movie
- [x] It should show basic meta data (year, genre, duration)
- [x] It should have a synopsis of the movie
- [x] It should have a link and review from IMDb
- ~~It should have a link and review from Rotten Tomatoes~~
- [x] It should have a link and review from Meta Critic
- ~~It should take the user to Fandango when they select the row~~

**Comment by chuckharmston** [comment]
The [data source](http://omdbapi.com/) I've been working with currently provides the following:

```json
{
  "Title": "The Martian",
  "Year": "2015",
  "Rated": "PG-13",
  "Released": "02 Oct 2015",
  "Runtime": "144 min",
  "Genre": "Adventure, Drama, Sci-Fi",
  "Director": "Ridley Scott",
  "Writer": "Drew Goddard (screenplay), Andy Weir (book)",
  "Actors": "Matt Damon, Jessica Chastain, Kristen Wiig, Jeff Daniels",
  "Plot": "During a manned mission to Mars, Astronaut Mark Watney is presumed dead after a fierce storm and left behind by his crew. But Watney has survived and finds himself stranded and alone on the hostile planet. With only meager supplies, he must draw upon his ingenuity, wit and spirit to subsist and find a way to signal to Earth that he is alive.",
  "Language": "English, Mandarin",
  "Country": "USA, UK",
  "Awards": "Nominated for 7 Oscars. Another 34 wins & 163 nominations.",
  "Poster": "http:\/\/ia.media-imdb.com\/images\/M\/MV5BMTc2MTQ3MDA1Nl5BMl5BanBnXkFtZTgwODA3OTI4NjE@._V1_SX300.jpg",
  "Metascore": "80",
  "imdbRating": "8.1",
  "imdbVotes": "409,688",
  "imdbID": "tt3659388",
  "Type": "movie",
  "Response": "True"
}
```

**Comment by chuckharmston** [comment]
Rotten Tomatoes has an API from which we can get their ratings: http://developer.rottentomatoes.com/docs

**Comment by chuckharmston** [comment]
Fandango supposedly has an API, but registration is disabled and you can't access documentation without first authenticating: https://developer.fandango.com/page

**Comment by chuckharmston** [comment]
I'm going to move forward with this as proposed above, replacing Fandango with a link to IMDB and skipping Rotten Tomatoes. Please course correct if that seems wrong.

**Comment by bryanbell** [comment]
![rec - movie - captain](https://cloud.githubusercontent.com/assets/228979/15308052/038879b4-1b8e-11e6-9d02-28edc573b272.png)
how's this?
