### ISSUE TITLE
Classify searches for product pages

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/universal-search-recommendation#135]
- [ ] It should show results for things like cars, tablets, or phones
- [ ] It should show the official product page 
- [ ] It should have a picture of the product

**Comment by chuckharmston** [comment]
The methodology for this will be interesting. I've done some research, and it seems like the closest thing we can get to the recognition of a product page is by looking for the `<meta name="og:type" description="product"/>` tag, which is present on product pages on Zappos, Walmart, and Ikea, and it's missing on Amazon.

One question for product: how high-value do you think this is? I can't imagine a great number of top search results being for product pages.

And one proposal: we use the aforementioned opengraph tag, with special considerations for Amazon.

**Comment by 6a68** [comment]
OG product tags seem to get us halfway to "popular" products. We'll need some kind of canonical list, at least of popular product categories, if not popular products by brand.
