### ISSUE TITLE
Prune outliers in metrics

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/universal-search-recommendation#138]
> Additionally, we will discard outliers on a schedule:
> - Any queries that have only been made once.
> - Any queries longer than 6 characters that have been made less than 10% as frequently as the most common query of that length (e.g. if the most frequently-made 8-character query has been made 1000 times, all 8-character queries made fewer than 100 times will be discarded).

**Comment by chuckharmston** [comment]
The following query will select all queries of length `6` that should be deleted from table `universalsearch_server_20160510`. Preview [on re:dash](https://sql.telemetry.mozilla.org/queries/352/source).

```sql
WITH q1 AS
  (SELECT query,
          COUNT(query) AS max_query_count
   FROM universalsearch_server_20160510
   WHERE LENGTH(query) = 6
   GROUP BY query
   ORDER BY max_query_count DESC LIMIT 1),
     q2 AS
  (SELECT query,
          COUNT(query) AS query_count
   FROM universalsearch_server_20160510
   WHERE LENGTH(query) = 6
   GROUP BY query),
     q3 AS
  (SELECT ceiling(q1.max_query_count*.1) AS threshold
   FROM q1)
SELECT q2.query
FROM q2,
     q3
WHERE q2.query_count <= q3.threshold
```

Since we `ceililing` a number greater than 0 and use `<=` as a comparison operator with the calculated threshold, this satisfies both bullet points in the docs.

**Comment by chuckharmston** [comment]
I think next steps are on Wil, so assigning to him.

**Comment by wresuolc** [comment]
`WITH` is not supported on redshift: http://docs.aws.amazon.com/redshift/latest/dg/c_redshift-sql-implementated-differently.html

**Comment by wresuolc** [comment]
Alright, I have a script which deletes these rows, but I had two thoughts:

1) I probably shouldn't be deleting the rows.  Instead I should set the query to blank and set some boolean to true like the other rows.  So, I think we should add a predicates.unusual column to the schema, push that through to redshift, and then set that to true when the script hits.

2) I really like idempotent scripts and so far the one I wrote isn't.  Once we clear the top queries, if we run it again, it'll clear the next largest queries and so on.  I could track the dates the script was run for in a table somewhere, but that seems sloppy. :-/

/cc @chuckharmston for thoughts

**Comment by chuckharmston** [comment]
>  So, I think we should add a predicates.unusual column to the schema, push that through to redshift, and then set that to true when the script hits.

I really like that.

>  I could track the dates the script was run for in a table somewhere, but that seems sloppy. :-/

Procedurally, what will the process be? This script be run on a daily basis before moving data from S3 to Redshift? If so, can we just say that scrubbing happens between S3 and Redshift?

**Comment by wresuolc** [comment]
Update: The predicates.unusual column has been pushed through and defaults to false.  I still need to modify the script to take advantage of it.
