### ISSUE TITLE
Heartbeat endpoints should work without RECOMMENDATION_SERVER_NAME being set.

### ISSUE THREAD

**Issue by wresuolc** [mozilla/universal-search-recommendation#151]
This URL disappeared (404s now) with the movie cards push.  We need it functioning again before we can deploy to production.

 /cc @chuckharmston @6a68 @relud

**Comment by relud** [comment]
`/__heartbeat__` is also responding with 404s

**Comment by chuckharmston** [comment]
Updated bug title to reflect the actual bug.

**Comment by relud** [comment]
the root cause of this issue was identified:
with `RECOMMENDATION_SERVER_NAME=universalsearch.stage.mozaws.net` all endpoints are 404 unless the Host header is set to `universalsearch.stage.mozaws.net`.
