### ISSUE TITLE
Should we filter adult content?

### ISSUE THREAD

**Issue by 6a68** [mozilla/universal-search-recommendation#25]
We don't verify the user is above the age of consent, so I'm not sure we should be showing preview content (images/text) from adult sites in response to user keystrokes. I dunno. Maybe legal should be involved? cc @nchapman

Technically speaking, the BOSS [API docs](https://developer.yahoo.com/boss/search/boss_api_guide/web.html#filter) mention filters for 'porn' and 'hate', but only provide an example for 'porn':
```
https://yboss.yahooapis.com/ysearch/web?q={keywords}&format=xml&filter=-porn
```

`¯\_(ツ)_/¯`

**Comment by chuckharmston** [comment]
As a representative of a user agent, I don't think we should default to doing any sort of filtering unless legal requests it, especially since we may want to expand beyond BOSS in the future, and other engines may not support the same types of filtering.

If we do need to implement this, we would probably want to do it in an off-by-default setting in the addon.

**Comment by nchapman** [comment]
I totally get the user agent argument but from the user's perspective, Firefox is giving you recommendations. I think avoiding accidental porn in the awesomebar is a reasonable thing to do :smile:. I think we can have a much more nuanced opinion about this as we become more sophisticated at curating results. For the sake of all early tests, I think we should err on the conservative side.

I want to say that BOSS has the porn filter on by default, but I might be remembering that incorrectly.

**Comment by chuckharmston** [comment]
I still think we should avoid doing anything remotely resembling censorship; it'd be one thing if we were acting as a third-party service, but we're developing behavior that we want to be built-in to a web browser some day. That said, I do concede that accidental porn is a bad experience.

Proposal: let's make it configurable. Setting in the addon (I guess filter-by-default is fine), [configuration is passed to the content](https://github.com/mozilla/universal-search-addon/issues/188#issue-129181428), and that preference is relayed to the API.

**Comment by wresuolc** [comment]
Answer: yes. turn on safe search.

**Comment by 6a68** [comment]
Sounds great, closing this discussion bug in favor of #90, an implementation bug for our current API.

Thanks all!
