### ISSUE TITLE
Develop strategies for prepopulating cache.

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/universal-search-recommendation#28]
We should write a command that prepopulates the cache based on some combination of a list of common/popular searches and short combinations of characters.

**Comment by chuckharmston** [comment]
The latter could be done rather easily:

```python
from itertools import chain, product
from string import ascii_lowercase


def combinations(length, combination_set=ascii_lowercase):
    """
    Generates a list of all `length`-character combinations of the passed 
    `combination_set`.

    >>> combinations(1)
    ['a', 'b', 'c', 'd', '...', 'x', 'y', 'z']

    >>> combinations(2)
    ['aa', 'ab', 'ac', 'ad', '...', 'zx', 'zy', 'zz']

    >>> combinations(2, combination_set='abcde')
    ['aaa', 'aab', 'aac', 'aad', '...', 'eec', 'eed', 'eee']
    """
    return [''.join(combination) for combination in
            product(combination_set, repeat=length)]


def flatten(lists):
    """
    Flattens a series of nested lists.

    >>> flatten([[1, 2], [3, 4]])
    [1, 2, 3, 4]
    """
    return list(chain(*lists))


def letter_sequences(max_length):
    """
    Returns a list containing all combinations of lowercase ASCII letters
    between 1 and `max_length` characters long.

    >>> letter_sequences(4)
    ['a', 'b', 'c', 'd', '...', 'zzzx', 'zzzy', 'zzzz']
    """
    return flatten([letter_combinations(length) for length in
                    range(1, max_length)])
```

**Comment by chuckharmston** [comment]
Assigning to Nick for triage as discussed in the planning meeting today.

**Comment by nchapman** [comment]
Let's use the top 1000 [Alexa sites](http://s3.amazonaws.com/alexa-static/top-1m.csv.zip) and the [top 250 Wikipedia pages](https://en.wikipedia.org/wiki/User:West.andrew.g/Popular_pages).

**Comment by nchapman** [comment]
1. We should explode each query (facebook becomes f, fa, fac, face...)
2. Use the first segment of the domain from alexa (`^[^\.]+`)
3. Use the top 250 Wikipedia page titles with a 10 character limit

**Comment by chuckharmston** [comment]
@nchapman Did you have a source in mind for the wikipedia pages? I haven't been able to find anything, official or otherwise.

**Comment by nchapman** [comment]
The popular Wikipedia pages I linked too seems to be kept up-to-date:

https://en.wikipedia.org/wiki/User:West.andrew.g/Popular_pages

**Comment by chuckharmston** [comment]
Ah, I missed the link entirely. Sorry!

**Comment by nchapman** [comment]
Haha no problem!
