### ISSUE TITLE
Add heartbeat endpoints

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/universal-search-recommendation#34]
Copied from https://github.com/mozilla/universal-search/issues/1

The operations infrastructure is expecting some endpoints for each project to reply in a standardized fashion.  This will be expected for all Test Pilot experiments as well as Test Pilot itself.  They are handy for debugging too!

<s>1. Respond to /__version__ with a [JSON version object](https://docs.google.com/document/d/1rGVyiLYvZyKE2oHcSVx-vBmQRKhs1kLLgn7xeCs6qKs/edit)</s> (moved to #41).
2. Respond to /__heartbeat__ with a HTTP 200 or 5xx on error

    this endpoint is used by external monitoring to check the health of the service
    it is recommended to check the app's dependencies (database, caches, etc) here

3. Respond to /__lbheartbeat__ with an HTTP 200

    used by the load balancer to check if the server and application is OK
    do not include dependency checks as this check may trigger automatic node termination and replacement

**Comment by lmorchard** [comment]
FWIW, [in the Dockerflow spec](https://github.com/mozilla-services/Dockerflow#a-containerized-app-must), these routes are meant to have literal double-underscores, like so:
```
/__lbheartbeat__
/__heartbeat__
/__version__
```
These show up as __bold__ in Markdown, but are meant to be literal.

**Comment by chuckharmston** [comment]
Hah! Good catch. Filed #46
