### ISSUE TITLE
Server-side metrics collection

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/universal-search-recommendation#35]
As defined here: https://github.com/mozilla/universal-search/blob/master/docs/metrics.md#on-the-server

**Comment by chuckharmston** [comment]
Assigning to Nick for triage as discussed in the planning meeting today.

**Comment by clouserw** [comment]
Should have something for this soon.

See also https://github.com/mozilla/universal-search/issues/18

**Comment by chuckharmston** [comment]
See https://github.com/mozilla/universal-search/pull/79
