### ISSUE TITLE
Get images from `apple-touch-icon` and/or `og:image`.

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/universal-search-recommendation#5]
Suggested approach:

- In `SearchRecommendation`, after the `result` property is determined, but before the classifiers are applied, do an HTTP request for `result.url` and store the DOM on a property of the `SearchRecommendation` instance.
- Pass the DOM during the construction of each classifier instance for the result.
- Have helpers on the base classifier to help with the querying of the DOM.
- Each classifier will then have the ability to query the DOM as necessary.
- A new classifier can be written to get the apple touch icon for websites, and a separate classifier can be written to get the `og:image` for article-type content.

**Comment by 6a68** [comment]
@chuckharmston I'm not sure I fully understand the motivation for this one. Would you mind providing a high level explanation?

**Comment by chuckharmston** [comment]
Closing this; we're using external APIs to do this work for us for now.
