### ISSUE TITLE
Refactor to Dockerflow-compliant single-container application.

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/universal-search-recommendation#51]
The original plan was to use a multiple-container Docker configuration and use one of AWS' services that allow multiple-container deployment. That's changed, and we've now been asked to use [Dockerflow](https://github.com/mozilla-services/Dockerflow), which is a substantial departure. I've tried to reuse as much work as possible, but there have been enough gotchas that I've talked myself into starting over with the production architecture in mind.

This bug will track design efforts, and bugs resulting from it will be tracked in the [Deployment-ready milestone](https://github.com/mozilla/universal-search-recommendation/milestones/Deployment-ready).

### Desired end state:

- On successful builds on `master`, CI will build the application into a Docker container that is then published to Docker Hub and deployed.
- The built container is [Dockerflow](https://github.com/mozilla-services/Dockerflow)-compliant.
- Local development is as contributor-friendly as possible.

### Proposal:

- Refactor from a multiple-container configuration to a single-container one that only manages the application.
- For local development, use a [Compose](https://docs.docker.com/compose/) configuration that manages data storage and task queues.
- Eliminate nginx entirely; use uWSGI directly as a server, and use Flask's [`send-file`](http://flask.pocoo.org/docs/0.10/api/#flask.send_file) for our few static files.

Feedback wanted: @mostlygeek @6a68

**Comment by mostlygeek** [comment]
You assigned this to me, not quite sure what you want me to do. :) 
I'm +1 on using Dockerflow and the proposal above.

**Comment by chuckharmston** [comment]
Mostly just feedback, since we talked a lot yesterday and I wanted to make sure I'd condensed everything into an appropriate, concrete plan. Thanks @mostlygeek!
