### ISSUE TITLE
Remove Yahoo! BOSS Search references

### ISSUE THREAD

**Issue by pdehaan** [mozilla/universal-search-recommendation#69]
# TL;DR: Access to the BOSS APIs will continue until _**March 31, 2016**_.

---

Per discussions in https://github.com/mozilla/universal-search-recommendation/pull/66.

> I'm going to keep Yahoo around for now, since the plan is apparently to keep riding those coattails as long as we are able.

Looks like the BOSS service will be removed in ~2 weeks, according to https://developer.yahoo.com/boss/search/:

> _"At Yahoo, we’re always looking for ways to streamline and simplify products for our customers. With this focus in mind, we will discontinue the BOSS JSON Search API on **March 31, 2016**._

> _Access to the BOSS APIs will continue until **March 31, 2016**. Moving forward, customers leveraging the BOSS JSON Search API can instead use YPA, a Javascript Solution that provides algorithmic web results with search ads for publishers who manage their own search engine results pages (SERPs). Click here to apply or learn more about YPA, or if you are working with a Yahoo Partner Manager, they can help you explore your options."_

**Comment by 6a68** [comment]
The API is still working, so we'll probably use it until it disappears without warning. Closing this issue.
