### ISSUE TITLE
Reconsider conditions under which Embedly data is included

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/universal-search-recommendation#78]
In #63, we temporarily turned `EmbedlyClassifier` on for all results in order to get access to favicons for every site. In #77, we will revert those changes when adding a new classifier solely responsible for dealing with favicons. That means we will see other Embedly data—most notably key images—for results where `EmbedlyClassifier` is not applied.

When toying around with it, that feels a lot worse. One example of that:

<img width="297" alt="screen shot 2016-03-24 at 4 38 09 pm" src="https://cloud.githubusercontent.com/assets/23885/14033302/fe6342b2-f1de-11e5-8b55-74fa836fb1dc.png"> <img width="307" alt="screen shot 2016-03-24 at 4 33 17 pm" src="https://cloud.githubusercontent.com/assets/23885/14033210/3794ee7e-f1de-11e5-844f-c54bef250d0f.png">

Embedly data is currently included for top level domains, directories, and Wikipedia articles. We don't want to always include it—there are quite a few bytes involved in that—but we could definitely afford to expand the current definition.

**Comment by chuckharmston** [comment]
One possibility: scrape the value of the `content` attribute of any `<meta property="og:type">` tags in the DOM of the recommendation URL. If it's one of `music.song`, `music.album`, `video.movie`, `video.episode`, `video.tv_show`, `article`, `book`, or `profile`, there's a pretty good chance that there's a relevant key image to snag from Embedly.

**Comment by chuckharmston** [comment]
cc @nchapman @6a68

**Comment by nchapman** [comment]
> We don't want to always include it—there are quite a few bytes involved in that

Could we choose to only keep/transmit the Embedly data that we're interested in and throw the rest out?

**Comment by chuckharmston** [comment]
We could, and do. In some types of content though, the key images will be irrelevant or won't make any sense (see: gigantic pictures of @nchapman all over my new tab page). I think we want to be a little more precise about when we want to display them, and the idea I had above requires that to be done on the server side, rather than by the add-on.

**Comment by nchapman** [comment]
I would like to have images as often as possible so I think we should always include the Embedly data for now. We can develop a more nuanced solution (curated ignore list) as the test progresses.
