### ISSUE TITLE
Load testing

### ISSUE THREAD

**Issue by 6a68** [mozilla/universal-search-recommendation#88]
_This issue was originally posted as https://github.com/mozilla/universal-search/issues/120 on the universal-search repo, moved to the server repo._

@wresuolc said:

> We talked about this in a meeting, but I forget which one.
> 
> Now that we have stage, we should run a load tester on it to get a rough idea of what kind of performance we can expect. Even if it's just returning nulls from memcache, it would be helpful to get a rough idea of requests/sec.
> 
> Ideally testing this won't cost us a fortune in API queries. :)

@chuckharmston replied:

> I don't think we should consider this until we have some sort of upstream cache; either Varnish-like or a CDN.
> 
> We could avoid costing us money in API queries by disallowing outbound HTTP requests from the worker server. All the jobs would fail, but as far as load testing the application server, it should be fine (still 1 memcached read per request).

**Comment by chuckharmston** [comment]
We should be good to start this. Make sure that @mostlygeek is notified ahead of time.

**Comment by chuckharmston** [comment]
@mostlygeek could we get you to set up a clone of the production environment for this? As mentioned above, ideally outbound HTTP and HTTPS would be disabled on the worker box; our jobs will all fail, but that's fine, we just want to blast the webhead with incoming traffic, and the net effect on the stack shouldn't change much. We don't need any fancy hostnames; aws-1234567890-abcdef-us-west-1.aws-abcdefghijklmnoqrstuvwxyz.com would be totally fine.

**Comment by mostlygeek** [comment]
Do you guys just want to load test the stage deployment? It already is a clone of the production stack. 

What is the testing method? 
There's autoscaling at the ELB and the EC2 layer. Plus caching at the nginx layer. These will likely give weird results if not accounted for.

**Comment by chuckharmston** [comment]
We're not going to get this done before public launch, and since a downed server will not break Firefox, I'm going to remove the launch blocker label.
